## NumPy (Numerical Python)

In [4]:
## numpy contains arrays and matrix data type

In [4]:
import numpy as np

In [8]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [10]:
## tuples
arr1 = np.array((1,2,3,4,5,6))
print(arr1)
print(type(arr1))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [12]:
## dimension of array

In [18]:
arr2 = np.array(20)
print(arr2)
print("the dimension of array is: ",arr2.ndim)

20
the dimension of array is:  0


In [20]:
## 1-D array


In [22]:
arr3 = np.array([1,2,3,4,5])
print(arr3)
print(arr3.ndim)

[1 2 3 4 5]
1


In [24]:
## 2-D array

In [32]:
arr4 = np.array([[2,3,7], [4,5,6]])
print(arr4)
print(arr4.ndim)

[[2 3 7]
 [4 5 6]]
2


In [34]:
## 3-D array

In [52]:
arr5 = np.array([[[1,2,3],[2,3,4], [4,5,6]]])
print(arr5)
print(arr5.ndim)

[[[1 2 3]
  [2 3 4]
  [4 5 6]]]
3


In [54]:
arr6 = np.array([1,2,3,4], ndmin = 5)
print(arr6)
print(arr6.ndim)

[[[[[1 2 3 4]]]]]
5


In [58]:
## indexing in 1-D array
arr7 = np.array([2,3,4,5,6,7,8,6,7,8,93])
print(arr7[2])
print(arr7[3] + arr7[6] + arr7[8])

4
20


In [60]:
## indexing in 2-D ARRAY

In [80]:
arr8 = np.array([[2,3,7 ,5,6], [4,9,6,6,7]])
print(arr8)
print(arr8[1,4]) ## syntax : [row , col]

[[2 3 7 5 6]
 [4 9 6 6 7]]
7


In [82]:
arr8 = np.array([[2,3,7 ,5,6], [4,9,6,6,7]])
print(arr8)
print(arr8[0,4]) ## syntax : [row , col]

[[2 3 7 5 6]
 [4 9 6 6 7]]
6


In [7]:
arr8 = np.array([[2,3,7 ,5,6], [4,9,6,6,7]])
print(arr8)
print(arr8[0,0] + arr8[1,4])

[[2 3 7 5 6]
 [4 9 6 6 7]]
9


## 3D- Arrays 

In [14]:
arr9 = np.array([[[1,2,3,4,5], [4,5,6,7,8], [9,6,4,3,7]]])
print(arr9)
print(arr9[0,1,2])

[[[1 2 3 4 5]
  [4 5 6 7 8]
  [9 6 4 3 7]]]
6


In [17]:
## slicing of numpy arrays

In [21]:
arr1 = np.array([23,4,5,6,7])
print(arr1[1:4])

[4 5 6]


In [25]:
## slicing for 2d
arr2 = np.array([[2,3,7 ,5,6], [4,9,6,6,7]])
print(arr2)

print(arr2[1,1:4])  ## [row number , normal slicing index]

[[2 3 7 5 6]
 [4 9 6 6 7]]
[9 6 6]


In [27]:
## slicing in 3d
arr3 = np.array([[[1,2,3,4,5], [4,5,6,7,8], [9,6,4,3,7]]])
print(arr3)
print(arr3[0,1,1:4])

[[[1 2 3 4 5]
  [4 5 6 7 8]
  [9 6 4 3 7]]]
[5 6 7]


In [31]:
arr3 = np.array([[[1,2,3,4,5], [4,5,6,7,8], [9,6,4,3,7]]])
print(arr3)
print(arr3[1,1,1:4])

[[[1 2 3 4 5]
  [4 5 6 7 8]
  [9 6 4 3 7]]]


IndexError: index 1 is out of bounds for axis 0 with size 1

 ## checking data types in array

In [36]:
arr = np.array([23,4,5,6,7])
print(arr.dtype)

int32


In [38]:
arr = np.array(['animls' , 'bat'])
print(arr.dtype)

<U6


In [40]:
## creating arrays with defined arrays
arr = np.array([5,6,7,8,3] , dtype = 'S')
print(arr)
print(arr.dtype)

[b'5' b'6' b'7' b'8' b'3']
|S1


In [44]:
## create array with data type 4byte integer
arr = np.array([1,2,3,4] , dtype = 'i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


## numpy shapes

In [47]:
 arr = np.array([[1,2,3,4], [5,6,7,8]])
print(arr.shape)

(2, 4)


In [51]:
 arr = np.array([[[1,2,3,4], [5,6,7,8], [3,4,5,6]]])
print(arr.shape)

(1, 3, 4)


In [55]:
## joining numpy arrays 1D
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr3 = np.concatenate((arr1,arr2))
print(arr3)

[1 2 3 4 5 6 7 8]


In [59]:
## joining numpy arrays 2D
arr1 = np.array([[2,3,7 ,5,6], [4,9,6,6,7]])
arr2 = np.array([[1,3,7 ,5,9], [4,9,6,5,7]])

arr3 = np.concatenate((arr1 , arr2) , axis = 1)
print(arr3)

[[2 3 7 5 6 1 3 7 5 9]
 [4 9 6 6 7 4 9 6 5 7]]


In [61]:
## joining numpy arrays 2D
arr1 = np.array([[2,3,7 ,5,6], [4,9,6,6,7]])
arr2 = np.array([[1,3,7 ,5,9], [4,9,6,5,7]])

arr3 = np.concatenate((arr1 , arr2) , axis = 0)
print(arr3)

[[2 3 7 5 6]
 [4 9 6 6 7]
 [1 3 7 5 9]
 [4 9 6 5 7]]


## spitting numpy arrays - > ek array ko alg alg tod dena



In [64]:
arr = np.array([1,2,3,4,5,6])
arr1 = np.array_split(arr, 3)
print(arr1)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [66]:
arr = np.array([1,2,3,4,5,6])
arr1 = np.array_split(arr, 4)
print(arr1)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


## ravel and flatten -> coverts multi dimensional to 1d array

In [74]:
m = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print(m)
print("dimension is: ", m.ndim)
n = m.ravel()
print(n)
print("new dimension is:", n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension is:  3
[1 2 3 4 5 6 7 8 9]
new dimension is: 1


In [76]:
m = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print(m)
print("dimension is: ", m.ndim)
n = m.flatten()
print(n)
print("new dimension is:", n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension is:  3
[1 2 3 4 5 6 7 8 9]
new dimension is: 1


In [88]:
m = np.array([[[[1,2,3], [4,5,6], [7,8,9] , [23,45,67]]]])
print(m)
print("dimension is: ", m.ndim)
n = m.ravel()
print(n)
print("new dimension is:", n.ndim)

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [23 45 67]]]]
dimension is:  4
[ 1  2  3  4  5  6  7  8  9 23 45 67]
new dimension is: 1


In [6]:
## unique function
k = np.array([12,3,4,54,5,67,89,5,6,7,4,2,4,4,5,7,54])
print(k)
x = np.unique(k, return_index = True)
print(x)

[12  3  4 54  5 67 89  5  6  7  4  2  4  4  5  7 54]
(array([ 2,  3,  4,  5,  6,  7, 12, 54, 67, 89]), array([11,  1,  2,  4,  8,  9,  0,  3,  5,  6], dtype=int64))


In [10]:
k = np.array([12,3,4,54,5,67,89,5,6,7,4,2,4,4,5,7,54])
print(k)
x = np.unique(k, return_index = True , return_counts = True)
print(x)

[12  3  4 54  5 67 89  5  6  7  4  2  4  4  5  7 54]
(array([ 2,  3,  4,  5,  6,  7, 12, 54, 67, 89]), array([11,  1,  2,  4,  8,  9,  0,  3,  5,  6], dtype=int64), array([1, 1, 4, 3, 1, 2, 1, 2, 1, 1], dtype=int64))


In [12]:
## delete

In [20]:
k1 = np.array([12,3,4,54,5,67,89,5,6,7,4,2,4,4,5,7,54])
k2 = np.delete(k1, [2])
print(k2)

[12  3 54  5 67 89  5  6  7  4  2  4  4  5  7 54]


In [30]:
m = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print(m)
n = np.delete(m ,1, axis = 1)
print(n)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [7 8 9]]]
